Repository futureleadersupc/waw-landing-page, pull requests merged in 2022-05, with the labels that each got.

#12 feat: Added pricing section
  index.html
  styles/main.css
Labels: enhancement

#13 chore: setup links in navbar
  index.html
Labels: chore

#14 feat: added placeholders for videos section
  index.html
Labels: enhancement

#17 fix: update the photo of the team
  img/waw.png
Labels: bug
