Repository futureleadersupc/waw-landing-page, pull requests merged in 2022-04, with the labels that each got.

#1 chore: initial setup of project
  .editorconfig
  index.html
  scripts/main.js
  styles/main.css
Labels: good first issue

#2 fix: added missing doctype
  index.html
Labels: bug

#6 feat: about us
  img/waw.png
  index.html
Labels: enhancement

#8 revert: #6
  img/waw.png
  index.html
Labels: bug

#9 chore: added `/img` folder
  .gitignore
  img/.gitkeep
Labels: enhancement

#10 feat: about-us
  img/waw.png
  index.html
Labels: enhancement

#7 feat: main-page
  img/main-page.jpg
  index.html
Labels: enhancement

#5 feat: Customer section added
  .idea/.gitignore
  .idea/modules.xml
  .idea/vcs.xml
  .idea/waw-landing-page.iml
  img/customer-logo-1.png
  img/customer-logo-2.png
  img/customer-logo-3.png
  img/customer-logo-4.png
  img/customer-logo-5.png
  img/customer-logo-6.png
  index.html
  scripts/main.js
  styles/main.css
Labels: enhancement
